"""Functions to dump castep .cell/.param files."""

from collections.abc import Iterable
from functools import singledispatch
from io import TextIOWrapper
from pathlib import Path
from typing import Any, TextIO


def dump_block(out: TextIO, block_name: str, data: Iterable):
    """Dump a block in castep .cell/.param format."""
    print(f"%block {block_name}", file=out)
    for row in data:
        print("\t".join(map(str, row)), file=out)
    print(f"%endblock {block_name}", file=out)
    print(file=out)


def dump_param(out: TextIO, param_name: str, data: Any):
    """Dump a block in castep .cell/.param format."""
    print(f"{param_name} = {data}", file=out)


@singledispatch
def castep_dumper(
    file,
    data: dict,
    source_file: str | None = None,
    source: str | None = None,
):
    """Dump file in .cell/.param format to file path."""
    raise NotImplementedError(f"Cannot dump to {type(file).__name__}")


@castep_dumper.register
def _(
    file: str,
    data: dict,
    source_file: str | None = None,
    source: str | None = None,
):
    castep_dumper(Path(file), data, source_file, source)


@castep_dumper.register
def _(
    file: Path,
    data: dict,
    source_file: str | None = None,
    source: str | None = None,
):
    with file.open("w", encoding="utf-8") as out_file:
        castep_dumper(out_file, data, source_file, source)


@castep_dumper.register
def _(
    file: TextIOWrapper,
    data: dict,
    source_file: str | None = None,
    source: str | None = None,
):
    """Dump file in .cell/.param format to file path."""
    print("# cell file generated by castep2cell.py", file=file)
    if source_file is None:
        print("Generated by castep_output_tools.", file=file)
    elif source is not None:
        print(f"# Generated from {source} calculation from {source_file}", file=file)
    else:
        print(f"# Generated from {source_file}", file=file)

    print(file=file)

    for key, val in data.items():
        dump_block(file, key, val) if isinstance(val, Iterable) else dump_param(file, key, val)
